### ISSUE TITLE
Rating: add rating to organisations and tools

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#1115]
We need to have the following addition on the backend:

1) We would like to have proper calculations of **contest** rating
2) To do this we need to have new fields in `LnkContestProject.kt: bestExecution: Execution` and `bestScore: Int` 
3) In Organization and Project entities we should have `totalScore` (or something like this - please check that these fields are not yet added). It should be taken as sum of the list of BEST EXECUTIONS 
4) When contest execution finishes - we update all these fields and rating

**Comment by kgevorkyan** [comment]
First phase:

* Pass type of execution to the backend
* Fill lnk_contest_execution
* Move `score` from lnk_contest_execution into the Execution entity

**Comment by petertrr** [comment]
> Move score from `lnk_contest_execution` into the Execution entity

I think the assumption there was that we'll only need scores in contests. Are you planning to change this?

**Comment by kgevorkyan** [comment]
> I think the assumption there was that we'll only need scores in contests. Are you planning to change this?

We decide with @akuleshov7 to move it anyway to Execution

**Comment by petertrr** [comment]
Ok, to clarify reasons - score will be used not only for contests, even if it's calculation may depend on the exact type of execution.

**Comment by petertrr** [comment]
>  It should be taken as sum of the list of BEST EXECUTIONS

Why do we need to sum all executions? For me this metric is not descriptive, because it mostly represents not the quality of the tool but rather how active they are using our platform. I think historical diagram of best score or variance of best scores over time may be a better option.

**Comment by petertrr** [comment]
The only thing that concerns me is that score in different contests may be calculated differently. Now we support only F-measure (i.e. combined precision and recall for warn-plugin-based tests), but we may have different types in the future. Then we'll need to change rules of aggregation and recalculated already stored values.

Right now, to calculate `contestRating` (this is the name of the field we already have) we can do something like
`contestRating = lnkContestProject.filter { it.project == this }.sumBy { bestScore }`

And to calculate organization rating,
`organizationRating = projects.findAllByOrganization(this).sumBy { it.contestRating} `

I think at least the latter can be calculated per request, because it doesn't involve a lot of data. `Project.contestRating` can be cahced as a column, however.

**Comment by petertrr** [comment]
For other plugins calculation of rating requires https://github.com/saveourtool/save-cli/issues/449

**Comment by petertrr** [comment]
https://github.com/saveourtool/save-cloud/pull/1162#discussion_r963028426

If we have `LnkContestProject.bestExecution` we don't need `LnkContestProject.bestScore`

**Comment by akuleshov7** [comment]
@petertrr what's left?

**Comment by petertrr** [comment]
Only a follow-up from https://github.com/saveourtool/save-cloud/pull/1162#discussion_r963028426, everything else is implemented

**Comment by akuleshov7** [comment]
@nulls can you please finalise it? :)
