### ISSUE TITLE
Invalid "batch size" input on the frontend

### ISSUE THREAD

**Issue by akuleshov7** [saveourtool/save-cloud#1833]
In the "batch size" window I cannot input numbers, but can input free text. 
That is definitely incorrect. 

<img width="1521" alt="image" src="https://user-images.githubusercontent.com/58667063/217069166-293f0997-e4fe-44ed-acbf-c9be2afd577d.png">

**Comment by sanyavertolet** [comment]
@akuleshov7 
In batch size input form `InputType` is used. `InputType` is used in order to provide the input type (thanks cap) to browser for it to check the input. It seems that `Safari` does no validation while `Chrome` allows using digits and `e` letter. It seems that the best idea is to remove browser validation and use our own (`value.all { it.isDigit() }`)
