### ISSUE TITLE
[DEMO] replace port-forwarding with Service

### ISSUE THREAD

**Issue by sanyavertolet** [saveourtool/save-cloud#1904]
Right now when we want to send request to `save-demo-agent` we initialize port-forwarding (and stop it on request completion) which is extremely slow. We either need to create a `Service` for each `save-demo-agent` (inside `save-demo` namespace using Kubernetes Client for example) or come up with an idea of creating one unified Service, probably some kind of `LoadBalancer`. Maybe @petertrr has an idea on this?🥺

**Comment by petertrr** [comment]
If you already have full info about pod, as I can see here


https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods

**Comment by petertrr** [comment]
If you already have full info about pod, as I can see here
https://github.com/saveourtool/save-cloud/blob/28f221b4ac0831a35c213cb8c5024fb7ee64f3df/save-demo/src/main/kotlin/com/saveourtool/save/demo/utils/HttpUtils.kt#L58

Then, if you also have access to Pod IP, you can use DNS record as described at https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pods

Otherwise, yes, you can create a Service that will have matching selectors with save-demo-agent pods and use it as a load balancer. If you still need to access specific pods, quoting from the same section of documentation:
> If there exists a headless Service in the same namespace as the Pod, with the same name as the subdomain, the cluster's DNS Server also returns A and/or AAAA records for the Pod's fully qualified hostname.
