### ISSUE TITLE
Grafana loki doesn't work

### ISSUE THREAD

**Issue by nulls** [saveourtool/save-cloud#1947]
Grafana cannot connect to `http://loki`

```
logger=context userId=1 orgId=1 uname=admin t=2023-03-07T11:06:11.879194976Z level=error msg="Failed to call resource" error="Get \"http://loki:3100/loki/api/v1/labels?start=1678186571442000000&end=1678187171442000000\": dial tcp: lookup loki on 10.247.3.10:53: no such host" traceID=
```

**Comment by akuleshov7** [comment]
@petertrr can you please help us one last time and briefly have a look on this? :)

**Comment by kgevorkyan** [comment]
related? https://github.com/saveourtool/save-cloud/pull/1936

**Comment by petertrr** [comment]
`kubectl --kubeconfig=config.cce --namespace=save-cloud get svc` shows, that service for loki with the port 3100 is now called `loki-headless`. Not sure which update causes it; at least since 4.5.0 with https://github.com/grafana/loki/commit/ef8b382c064ee8cb0dfb9b77e6387f1fb55185e0 they've started using full name for service name, which is why we have `save-cloud-loki` service that also exposes `3100`.

Btw, both promtail's target URL and URL in Grafana datasources have to be updated if switching to `loki-headless:3100` everywhere.

**Comment by akuleshov7** [comment]
> related? #1936

yes, definitely due to update

**Comment by nulls** [comment]
My plans:
1. Downgrade version of Grafana to working version in our environment
2. Extract Grafana to a dedicated chart to unbind from save-cloud chart and deploy
3. Try to extract `Grafana` related apps to a dedicated namespace
4. Continue to upgrade it when we will have a time
