### ISSUE TITLE
Bug with containers creation in Orchestrator on WSL

### ISSUE THREAD

**Issue by kgevorkyan** [saveourtool/save-cloud#728]
After https://github.com/analysis-dev/save-cloud/pull/707 there is a problems with `getHostIp()` method, since `host.docker.internal` on WSL are already exists in `/etc/hosts` for some reasons, therefore, in process of containers creation. instead of  `host-gateway` value we get  `host.docker.internal`, which is wrong

**Comment by petertrr** [comment]
IIUC, `host.docker.internal` on WSL distros points to the Windows hosts, so that processes from inside Docker on WSL distro can access processes running on Windows host and not on WSL VM. This can probably be worked around by passing `HOST_IP=host-gateway` when running orchestrator with `bootRun` inside WSL.

I believe if orchestrator runs on Windows and communicates with Docker Daemon via HTTP API (see #632), this very feature makes possible communication between agents running inside Docker for Windows and orchestrator. It's weird though, that there is a `hosts` entry even in usual distros.

**Comment by nulls** [comment]
We stopped build containers on orchestrator level
